=== JackieXie168/IPDR/ipdr/Collector/com/xacct/CRANE/collector/CRANEcollector.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.0.1 U (http://www.xmlspy.com) by Zohar Amir (Xacct Technologies/R&D) -->
<!-- $Id: CRANEcollector.xsd 2.100 2003/03/29 19:04:31 [release 2.1.2 2003-04-15T21-36-38Z] $ -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
 <xsd:element name="CRANEcollectorConfiguration">
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element name="Clients">
     <xsd:complexType>
      <xsd:sequence minOccurs="0" maxOccurs="unbounded">
       <xsd:element name="Client">
        <xsd:complexType>
         <xsd:sequence>
          <xsd:element name="IP">
           <xsd:annotation>
            <xsd:documentation>Client IP Address</xsd:documentation>
           </xsd:annotation>
           <xsd:simpleType>
            <xsd:restriction base="xsd:string">
             <xsd:minLength value="1"/>
            </xsd:restriction>
           </xsd:simpleType>
          </xsd:element>
          <xsd:element name="Port">
           <xsd:annotation>
            <xsd:documentation>Client port, if cannot be determined
            by version negotiation</xsd:documentation>
           </xsd:annotation>
           <xsd:simpleType>
            <xsd:restriction base="xsd:integer">
             <xsd:minInclusive value="0"/>
            </xsd:restriction>
           </xsd:simpleType>
          </xsd:element>
          <xsd:element name="VerPort">
           <xsd:annotation>
            <xsd:documentation>Client port used for version negotiation
            </xsd:documentation>
           </xsd:annotation>
           <xsd:simpleType>
            <xsd:restriction base="xsd:integer">
             <xsd:minInclusive value="0"/>
            </xsd:restriction>
           </xsd:simpleType>
          </xsd:element>
          <xsd:element name="VendorString" type="xsd:string">
           <xsd:annotation>
            <xsd:documentation>Client vendor string</xsd:documentation>
           </xsd:annotation>
          </xsd:element>
          <xsd:element name="CnctTO">
           <xsd:annotation>
            <xsd:documentation>How long to wait for a ProtocolInfoRequest to time out in
            milliseconds -- also used for timeouts when getting session
            and template information from the transmitter.  This is the
            overall time; the individual retries may be sent more often.
            </xsd:documentation>
           </xsd:annotation>
           <xsd:simpleType>
            <xsd:restriction base="xsd:integer"/>
           </xsd:simpleType>
          </xsd:element>
          <xsd:element name="CnctRetryTO">
           <xsd:annotation>
            <xsd:documentation>Connection retry timeout.
            How long to wait for between individual attempts to get
            ProtocolInfo in milliseconds. If no response is received
            within this time, another attempt will be made. The total
            number of attempts is controlled by connectTimeout.
            </xsd:documentation>
           </xsd:annotation>
           <xsd:simpleType>
            <xsd:restriction base="xsd:integer"/>
           </xsd:simpleType>
          </xsd:element>
          <xsd:element name="RecnctItvl">
           <xsd:annotation>
            <xsd:documentation>Connection reconnection interval.
            How long to wait before trying to connect again to the transmitter
            in milliseconds.
            </xsd:documentation>
           </xsd:annotation>
           <xsd:simpleType>
            <xsd:restriction base="xsd:integer"/>
           </xsd:simpleType>
          </xsd:element>
          <xsd:element name="CnctRndtrpTO">
           <xsd:annotation>
            <xsd:documentation>Connection round-trip timeout.
            How long to wait for between individual attempts to get
            ProtocolInfo in milliseconds. If no response is received
            within this time, another attempt will be made. The total
            number of attempts is controlled by connectTimeout.
            </xsd:documentation>
           </xsd:annotation>
           <xsd:simpleType>
            <xsd:restriction base="xsd:integer"/>
           </xsd:simpleType>
          </xsd:element>
          <xsd:element name="AckLogItvl">
           <xsd:annotation>
            <xsd:documentation>ACK log interval.
            Interval between outputting messages to the log about
            ACKs, in milliseconds.
            </xsd:documentation>
           </xsd:annotation>
           <xsd:simpleType>
            <xsd:restriction base="xsd:integer"/>
           </xsd:simpleType>
          </xsd:element>
          <xsd:element name="Desc" type="xsd:string">
           <xsd:annotation>
            <xsd:documentation>Session description.
            </xsd:documentation>
           </xsd:annotation>
          </xsd:element>
          <xsd:element name="Sessions">
           <xsd:complexType>
            <xsd:sequence minOccurs="0" maxOccurs="unbounded">
             <xsd:element name="Session">
              <xsd:complexType>
               <xsd:sequence>
                <xsd:element name="Id">
                 <xsd:simpleType>
                  <xsd:restriction base="xsd:integer">
                   <xsd:minInclusive value="0"/>
                  </xsd:restriction>
                 </xsd:simpleType>
                </xsd:element>
                <xsd:element name="Name" type="xsd:string"/>
                <xsd:element name="Desc" type="xsd:string"/>
                <xsd:element name="Tmplts">
                 <xsd:complexType>
                  <xsd:sequence minOccurs="0" maxOccurs="unbounded">
                   <xsd:element name="Tmpl">
                    <xsd:complexType>
                     <xsd:sequence>
                      <xsd:element name="TmplRef">
                       <xsd:simpleType>
                        <xsd:restriction base="xsd:string"/>
                       </xsd:simpleType>
                      </xsd:element>
                     </xsd:sequence>
                    </xsd:complexType>
                   </xsd:element>
                  </xsd:sequence>
                 </xsd:complexType>
                </xsd:element>
               </xsd:sequence>
              </xsd:complexType>
             </xsd:element>
            </xsd:sequence>
           </xsd:complexType>
          </xsd:element>
         </xsd:sequence>
        </xsd:complexType>
       </xsd:element>
      </xsd:sequence>
     </xsd:complexType>
    </xsd:element>
    <xsd:element name="Templates">
     <xsd:complexType>
      <xsd:sequence minOccurs="0" maxOccurs="unbounded">
       <xsd:element name="Template">
        <xsd:complexType>
         <xsd:sequence>
          <xsd:element name="GlobalRef">
           <xsd:simpleType>
            <xsd:restriction base="xsd:string"/>
           </xsd:simpleType>
          </xsd:element>
          <xsd:element name="Id">
           <xsd:simpleType>
            <xsd:restriction base="xsd:integer"/>
           </xsd:simpleType>
          </xsd:element>
          <xsd:element name="Desc">
           <xsd:simpleType>
            <xsd:restriction base="xsd:string">
             <xsd:minLength value="1"/>
            </xsd:restriction>
           </xsd:simpleType>
          </xsd:element>
          <xsd:element name="StatRsp">
           <xsd:simpleType>
            <xsd:restriction base="xsd:boolean"/>
           </xsd:simpleType>
          </xsd:element>
          <xsd:element name="Fields">
           <xsd:complexType>
            <xsd:sequence maxOccurs="unbounded">
             <xsd:element name="Field">
              <xsd:complexType>
               <xsd:sequence>
                <xsd:element name="CrnKeyId">
                 <xsd:simpleType>
                  <xsd:restriction base="xsd:integer"/>
                 </xsd:simpleType>
                </xsd:element>
                <xsd:element name="FieldUsed" type="xsd:boolean"/>
                <xsd:element name="CrnKeyName">
                 <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                   <xsd:minLength value="1"/>
                  </xsd:restriction>
                 </xsd:simpleType>
                </xsd:element>
                <xsd:element name="CrnKeyLabel">
                 <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                   <xsd:minLength value="1"/>
                  </xsd:restriction>
                 </xsd:simpleType>
                </xsd:element>
                <xsd:element name="CrnKeyHelp">
                 <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                   <xsd:minLength value="1"/>
                  </xsd:restriction>
                 </xsd:simpleType>
                </xsd:element>
                <xsd:element name="CrnKeyTypeId">
                 <xsd:simpleType>
                  <xsd:restriction base="xsd:integer">
                   <xsd:minInclusive value="0"/>
                  </xsd:restriction>
                 </xsd:simpleType>
                </xsd:element>
                <xsd:element name="XFieldId" minOccurs="0">
                 <xsd:simpleType>
                  <xsd:restriction base="xsd:integer"/>
                 </xsd:simpleType>
                </xsd:element>
                <xsd:element name="XFieldLabel" type="xsd:string" minOccurs="0"/>
                <xsd:element name="XFieldType" minOccurs="0">
                 <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                   <xsd:enumeration value="Integer"/>
                   <xsd:enumeration value="String"/>
                   <xsd:enumeration value="Boolean"/>
                   <xsd:enumeration value="Short"/>
                   <xsd:enumeration value="Long"/>
                   <xsd:enumeration value="Date"/>
                   <xsd:enumeration value="Double"/>
                   <xsd:enumeration value="Float"/>
                   <xsd:enumeration value="IP Address"/>
                  </xsd:restriction>
                 </xsd:simpleType>
                </xsd:element>
               </xsd:sequence>
              </xsd:complexType>
             </xsd:element>
            </xsd:sequence>
           </xsd:complexType>
          </xsd:element>
         </xsd:sequence>
        </xsd:complexType>
       </xsd:element>
      </xsd:sequence>
     </xsd:complexType>
    </xsd:element>
    <xsd:element name="ConfigurationVersion" type="xsd:string"/>
    <xsd:element name="ServerIPAddress" type="xsd:string"/>
    <xsd:element name="ServerPort">
     <xsd:annotation>
      <xsd:documentation>
       The collector's (server's) "port". This is not really a port
       in the TCP/IP sense; but is instead used with the CONNECT
       message as the "Server Port" field. Typically, this is used by
       the transmitter (client) to distinguish between multiple
       connections from the same IP address (that is, we can run
       multiple collectors on the same machine without multi-homing
       the IP address).
      </xsd:documentation>
     </xsd:annotation>
     <xsd:simpleType>
      <xsd:restriction base="xsd:integer"/>
     </xsd:simpleType>
    </xsd:element>
    <xsd:element name="ServerAckInterval">
     <xsd:annotation>
      <xsd:documentation>
      How often to send an ack to a transmitter (client).
      </xsd:documentation>
     </xsd:annotation>
     <xsd:simpleType>
      <xsd:restriction base="xsd:integer"/>
     </xsd:simpleType>
    </xsd:element>
    <xsd:element name="ServerStartInterval">
     <xsd:annotation>
      <xsd:documentation>
       Interval to wait between starting threads, to avoid
       a burst of activity at the beginning.
      </xsd:documentation>
     </xsd:annotation>
     <xsd:simpleType>
      <xsd:restriction base="xsd:integer"/>
     </xsd:simpleType>
    </xsd:element>
    <xsd:element name="EnableDebugMsg" type="xsd:boolean"/>
    <xsd:element name="NoDataKeepAliveInterval" minOccurs="0" maxOccurs="1">
     <xsd:annotation>
      <xsd:documentation>
       If no data arrives within this time, send a "keep-alive".
      </xsd:documentation>
     </xsd:annotation>
    </xsd:element>
   </xsd:sequence>
  </xsd:complexType>
 </xsd:element>
</xsd:schema>

=== JackieXie168/IPDR/ipdr/Collector/com/xacct/CRANE/collector/CRANEcollector_skeleton.xml
<?xml version="1.0" encoding="UTF-8"?>
<CRANEcollectorConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CRANEcollector.xsd">
  <Clients>
    <Client>
      <IP>192.168.69.20</IP>
      <Port>17000</Port>
      <VerPort>17000</VerPort>
      <VendorString/>
      <CnctTO>5000</CnctTO>
      <CnctRetryTO>2000</CnctRetryTO>
      <RecnctItvl>10000</RecnctItvl>
      <CnctRndtrpTO>2000</CnctRndtrpTO>
      <AckLogItvl>60000</AckLogItvl>
      <Desc/>
      <Sessions/>
    </Client>
  </Clients>
  <Templates/>
  <ConfigurationVersion>1</ConfigurationVersion>
  <ServerIPAddress/>
  <ServerPort>15001</ServerPort>
  <ServerAckInterval>1000</ServerAckInterval>
  <ServerStartInterval>10</ServerStartInterval>
  <EnableDebugMsg>false</EnableDebugMsg>
</CRANEcollectorConfiguration>
